### ISSUE TITLE
主线程刷新 循环失效

### ISSUE THREAD

**Issue by Vincentzzg** [NianJi/NJCycleScrollView#1]
有一种情况会导致循环失效。
如果vc中view中第一层是一个scrollView，然后CycleScrollView加在了这个scrollView中，scrollView拖动的过程中（或者手指只是点在scrollView上），CycleScrollView的循环就会停止，CycleScrollView中的计时器不会再调用。
我觉得这个应该是主线程的问题，所有的UI刷新必须在主线程，然后vc中scrollView的刷新阻塞了主线程，所以CycleScrollView中的计时器才会失效，不知道我理解的对不对。
请问这种情况有没有什么办法可以解决？

**Comment by NianJi** [comment]
fixed in: 91742e0c520ec20db0a190e61dbf7382b33be2c7

**Comment by Vincentzzg** [comment]
没想到改起来竟这么简单一句代码就搞定了
